[package]
name = "app"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
